---
title: "Intruducción a R"
author: "Laia Egea e Iago Giné"
date: "10-12/12/2019"
abstract: "El objetivo de este curso es introducir el software R a todas las personas que trabajen con datos y darles las herramientas para el manejo y visualización de datos, así como para algunos análisis estadísticos básicos."
output: 
  html_notebook:
    toc: yes

---

# Presentación del entorno R y Rstudio

* R y RStudio son dos programas diferentes. 
    + R es el programa que calcula. Es software libre y gratuito, inicialmente enfocado a la computación estadística.
    + R también es el lenguaje en el que escribimos los comandos, pues es también el lenguaje de programación.
    + Hoy en día está ampliamente extendido y entre los lenguajes de programación más utilizados. Como consecuencia:
        * existen muchos foros en internet donde los usuarios plantean/resuelven sus dudas y/o propuestas.
        * hay muchas librerías para R en continuo desarrollo y que permiten usarlo de una manera mucho más rápida y eficiente.
    + RStudio es la interfaz donde estaremos trabajando, pues nos ofrece algunas comodidades.
        * Nos permite crear scripts de una manera más ágil y en un entorno mucho más agradable que usando R.
        * También hace más sencillo instalar y desinstalar librerías, cargar y visualizar bases de datos, etc.
        * Ofrece otras posibilidades más allá de R como crear páginas web, pdf's o archivos word con R integrado, que va más allá de este curso.

* Entre las consecuencias de lo ampliamente usado de R está que podemos encontrar en internet muchos tutoriales introductorios en cualquier idioma:
    * [http://rosuda.org/mitarbeiter/pilhoefer/rkurs2.pdf](http://rosuda.org/mitarbeiter/pilhoefer/rkurs2.pdf)
    * [http://b2slab.upc.edu/software-and-tutorials/r-nutshell/](http://b2slab.upc.edu/software-and-tutorials/r-nutshell/)
    * [https://www.cyclismo.org/tutorial/R/index.html](https://www.cyclismo.org/tutorial/R/index.html)
    * [https://www.uv.es/vcoll/preliminares.html](https://www.uv.es/vcoll/preliminares.html)
    * [http://people.math.aau.dk/~sorenh/misc/rdocs/Rintro-notes.pdf](http://people.math.aau.dk/~sorenh/misc/rdocs/Rintro-notes.pdf)

* ... y foros:
    + principalmente [https://stackoverflow.com/questions/tagged/r](https://stackoverflow.com/questions/tagged/r)
    + para cuestiones relacionadas con RStudio, pero también con las librerías de la familia tidyverse y otros: [https://community.rstudio.com/](https://community.rstudio.com/)

* ... y blogs:
    + principalmente: [https://www.r-bloggers.com/](https://www.r-bloggers.com/)
    + enfocado a la estadística: [http://www.sthda.com/english/](http://www.sthda.com/english/)
    
* ... y sobre librerías específicas:
    + ggplot
        * [http://www.flutterbys.com.au/stats/tut/tut5.2.html](http://www.flutterbys.com.au/stats/tut/tut5.2.html)

Entonces, este curso, para qué?



# Nociones elementales y funciones básicas

## R como calculadora

## Operadores aritméticos y lógicos
## Vectores y data frames 

# Funciones y librerías para interaccionar con otros softwares estadísticos como SPSS o STATA
# Manejo de datos con las librerías dplyr & tidyr 

## Selección y filtro de variables 
## Transformación de variables 
## Estadísticos descriptivos 

# Gráficos con la librería ggplot2
# Tests estadísticos y modelos de regresión habituales para el análisis estadístico
## T-test, anova... 
## Regresión lineal, logística, multinomial... 